spring:
  application:
    name: store
  config:
    import: optional:file:.env[.properties]
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 5 minutes
    refreshTokenExpiration: 604800 # 7 days
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}